title: Splines
author_name: Splines
description: >-
  Programming, music, physics, math... A little blog to document some learnings and ideas.

baseurl: "" # the subpath of your site, e.g. /blog
url: https://splines.me
permalink: /blog/:year/:title

collections:
  pages:
    output: true
    permalink: /:path/

# No theme: https://stackoverflow.com/a/57424621/

plugins:
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# https://minimalbb.github.io/cheat%20sheet/kramdown-markdown-guide-with-jekyll

kramdown:
  syntax_highlighter: nil
